name: Memory Check
on: push
jobs:
  memcheck:
    name: memcheck
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install Valgrind dependency
        # run: sudo snap install --classic valgrind
        run: sudo apt-get install -y libc6-dbg valgrind
      - name: tree
        run: sudo apt install -y tree
      - name: Build
        env:
          CC: gcc-9
          CXX: g++-9
        run: ./pleasew build //main:squiggles_memcheck
      - name: check for leaks
        run: valgrind --tool=memcheck --leak-check=full --leak-resolution=med --show-leak-kinds=all --undef-value-errors=yes --track-origins=yes  --error-exitcode=1 --show-reachable=no ./plz-out/bin/main/squiggles_memcheck
